name: NightVision
version: ${project.version}
main: me.noodles.nv.NightVision
authors: [BGHDDevelopment]
website: http://bghddevelopment.com/
commands:
  nv:
    description: Enable or Disable NV
    usage: /<command>